### ISSUE TITLE
Why don't you include 8? It's now an industry standard.

### ISSUE THREAD

**Issue by RyKilleen** [jackdcrawford/five#161]
This may be outside the scope of the project, but is it possible to expand to include 8? There's been a widespread push towards the use of 8 lately, and I think it will help this community in the long run.

**Comment by Aourin** [comment]
I think it you should keep in mind that 5 is meant as a 5 solution. What you could do is do is wrap the functionality and do five() + 3; It might be easier that way since this is a 5 based repo. Although, it is a concern that 8 is getting widespread, it might be better to fork and create a new 8 repo. The 8 repo could be an extension to use five.

**Comment by gre** [comment]
`five() + five() / five() + five() / five() + five() / five()`

**Comment by Joezo** [comment]
@gre has the perfect solution here, all you need is five :)

**Comment by tj-commits** [comment]
you can use the [`eight-toolkit`](https://npmjs.com/eight-toolkit) package and do `eightToolkit.constants.EIGHT`
